import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#dae2fd",
        "on-secondary-fixed-variant": "#38485d",
        "background": "#fcf8fa",
        "tertiary-fixed-dim": "#edc06e",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#d0e1fb",
        "surface-container-high": "#eae7e9",
        "secondary-fixed": "#d3e4fe",
        "primary-container": "#131b2e",
        "secondary": "#505f76",
        "error": "#ba1a1a",
        "surface-container-low": "#f6f3f5",
        "on-primary-fixed": "#131b2e",
        "on-error": "#ffffff",
        "tertiary": "#000000",
        "primary": "#000000",
        "on-background": "#1b1b1d",
        "outline-variant": "#c6c6cd",
        "surface-container-highest": "#e4e2e4",
        "on-primary-container": "#7c839b",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#54647a",
        "outline": "#76777d",
        "inverse-surface": "#303032",
        "on-primary-fixed-variant": "#3f465c",
        "inverse-primary": "#bec6e0",
        "tertiary-container": "#271900",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary-fixed": "#271900",
        "surface": "#fcf8fa",
        "on-secondary-fixed": "#0b1c30",
        "surface-dim": "#dcd9db",
        "on-surface": "#1b1b1d",
        "surface-bright": "#fcf8fa",
        "surface-container": "#f0edef",
        "surface-variant": "#e4e2e4",
        "tertiary-fixed": "#ffdea8",
        "on-tertiary-fixed-variant": "#5e4200",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#565e74",
        "inverse-on-surface": "#f3f0f2",
        "error-container": "#ffdad6",
        "on-surface-variant": "#45464d",
        "on-tertiary-container": "#a47e33",
        "primary-fixed-dim": "#bec6e0",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        gutter: "24px",
        "section-gap": "80px",
        "container-max": "1280px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
        base: "8px",
      },
      fontFamily: {
        "body-md": ["Manrope", "sans-serif"],
        "headline-lg": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "display-lg": ["Newsreader", "serif"],
        "body-lg": ["Manrope", "sans-serif"],
        serif: ["Newsreader", "serif"],
        sans: ["Manrope", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "label-sm": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "display-lg": [
          "48px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
export default config;
